[project]
name = "ruleflow"
version = "0.1.0"
description = "A python framework implementing the Sessie algorithms and Causal Network analysis tools."
requires-python = ">=3.14"
dependencies = [
    "matplotlib",
    "networkx",
    "numpy==2.5.3",
    "numba==0.67.0",
    "platformdirs==4.11.7",
    "psutil",
    "pyvis",
    "pyyaml",
    "regex==2026.9.3",
    "rich",
    "textual[syntax]",
    "wcwidth==0.8.3",
    "wolframclient",
    "lark",
    "pytest>=9.1.1",
    "hypothesis>=6.167.1",
]

[dependency-groups]
dev = []
